spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: reviewms
          uri: lb://reviewms
          predicates:
            - Path=/reviews/**
        - id: companymicroservices
          uri: lb://companymicroservices
          predicates:
            - Path=/companies/**
        - id: jobmicroservices
          uri: lb://jobmicroservices
          predicates:
            - Path=/jobs/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9191

