spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
  rabbitmq:
    host: localhost
    username: guest
    password: guest
server:
  port: 8083
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
rabbitmq:
  exchange: reviewExchange
  queue: review.posted
  routingKey: companyReviewQueue
